version: '3'
services:
  migrate:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    image: migrate:latest
    ports:
      - "9022:9002"
    volumes:
      - ./config:/migrate/config
