version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: ethereum-server:latest
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./src:/webportal_server/src
  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: '1234'
    ports:
      - "9001:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data